{% set name = "fredapi" %}
{% set version = "0.5.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/mortada/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e3298a263cc259de035f983da1cf853e7970ccc263c972d7a2c5313d0c3d5fe4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - wheel
  run:
    - pandas
    - python

test:
  requires:
    - pip
    - pytest
  imports:
    - fredapi
  source_files:
    - fredapi/tests
  commands:
    - pip check
    # test_with_proxies required FRED API key, which should be requested on site
    {% set ignore_tests = " --ignore=fredapi/tests/test_with_proxies.py" %}
    - pytest fredapi/tests -v {{ ignore_tests }}

about:
  home: https://github.com/mortada/fredapi
  dev_url: https://github.com/mortada/fredapi
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python API for Federal Reserve Economic Data (FRED) from St. Louis Fed

extra:
  recipe-maintainers:
    - tk3369
