travis:
  secure:
    BINSTAR_TOKEN: zoxNIJ872cB9/agrWzjJFgBiRLUarSAzfqja/70cxg2USs264N5X7ufH53uMVRUmy8wHTO7Eg+ytPOIiHcZVzx5p02u+opDcogRVnAG2wvqy8xTklHkGDIkNbPNvBJqml+5A8ZeJtIgPJqeAivdcTd3jgoIkam/k3gsLC5n6ZdaNrRT2idtG20WphfPBUnc1NSKtHQ82cH6X2s2i9kHfeBiaZ5Tp803uy0+xeXzne816saxYNQd3xtxvxgHPuEAIM2BYcsJ0spWUfCfOebpQgoetXgVMxjDe+osfTEcsKtTNwpUmZMunwaV3BztKr5XJIGQNsEQw//dtX/en3AnDIu+30gByqsQWoc1Yy9sWho9UqizZwt1eAMqebs+QPRvtJrOsajMj2oc9XbZwClWlcneupM4dS5KICm/OPMcmEWzNZxXORpPd992r+QkmlhskF5iTq59/r0Tvzce916vALSyZidyJHQG4k9owgBt1fFgr1BNg1G9LUPc9xJCBdJ0JLs+pzbUB/q6pppIaJXeIjOnFGym76WZDORC1iqWkVMcTswUE2n4xQvXdkt2/EC+cgCpUwfByJlIk4O16nAHecgeY2tuaoUxYDPF3Kqj+7aS+mtdoQVP4PaR2KU/YGMbGs5WbooVKqgOAl3GF6bHOY4lXl3HKtoTnhgqfywbvdf4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
