travis:
  secure:
    BINSTAR_TOKEN: W+srWGIfxCaG+Su8Wy1GMV5qfUi4iHIuKsECwFf9/cqvsaBM/wlbmKIF80m+M1veYEN1omZ1i4m4EMCY/S1PYsYQiidrgbjZCXX7fpG8G2JWQrZlJQ25XNvc60CMfgvO3c8kuq8GGxTPfzupvE2m0ZiE7qxIVfQjlc9aEJWqv9OGhso2dJAoB0C6oFtUWbciINCaiRFNfaHJJJT/486t4gFv7BJDkr1IU59PDdZDkev+BEubACKZZhyVVjhPQwDwjKOGA/n9vCZmIF1F9FxBMBLvxdfmWSMfuZ16xpJYHZSQfyNs74VerDSbLEpr29NizVBnSL4NvIcRsU02Xm1fhqm8Al5BQSrggtlLes9F6KqGQE3tlh6SwKmY/xvkD3q2v8HzCDlTUw4E3k6OzLY/RiP22r74zlMJ0IBRliE6XR5XMDVtoBLaY0OrEfVK0DqLi15MF272TN/4TmFByOTf0CO+oXRjX0+gO6BoRfD26tdKYD3Ul5QTiBgiRVdjswKVpzcZGF0cQe8mekhDhMfQ2YCytN8TZN9nKGhq5aD4y8dxhjOi31rgV2J0kKGcFx1hR8YK8/AlBl65J3TV/wFn4SuP0oqA58hKtFOsXUG3vQKlUzWeBg/eATnss9QXBAujcEOl1f3sRNv+3WVYFKupld9MQgpkDH+uoeaX4LrRt2c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
